spring:
  config:
    import: optional:file:env/.env.prod[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: error

management:
  endpoints:
    web:
      exposure:
        include: health,info
